version: '3'
services:
  cdk_java:
    container_name: cdk_java
    build:
      context: .
      dockerfile: Dockerfile
    user: 'circleci'
    working_dir: '/home/cdk'
    volumes:
      - './:/home/cdk'
      - '$HOME/.aws:/home/circleci/.aws'
    command: bash
    environment:
      - AWS_PROFILE=yukilab